name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "compassolisa_project"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            NODE_ENV
            MONGO_HOST
            MONGO_DB_NAME
            PORT
            SECRET
        env:
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_DB_NAME: compassolisa
          PORT: 3000
          NODE_ENV: prod
          SECRET: ${{ secrets.SECRET_KEY }}